// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assess_transform_cpp
double assess_transform_cpp(const arma::vec& xval, const arma::vec& yval, const arma::mat& coords, double theta, double htrans, double vtrans, int nrows, int ncols, arma::vec extent, int min_overlap);
RcppExport SEXP _thermal_assess_transform_cpp(SEXP xvalSEXP, SEXP yvalSEXP, SEXP coordsSEXP, SEXP thetaSEXP, SEXP htransSEXP, SEXP vtransSEXP, SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP extentSEXP, SEXP min_overlapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type xval(xvalSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yval(yvalSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type htrans(htransSEXP);
    Rcpp::traits::input_parameter< double >::type vtrans(vtransSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< int >::type min_overlap(min_overlapSEXP);
    rcpp_result_gen = Rcpp::wrap(assess_transform_cpp(xval, yval, coords, theta, htrans, vtrans, nrows, ncols, extent, min_overlap));
    return rcpp_result_gen;
END_RCPP
}
// assess_registration_cpp
double assess_registration_cpp(const arma::vec& params, arma::mat vcoords, const arma::vec& r2, const arma::vec& distortion_center, const arma::vec& vvalues, const arma::vec& tvalues, int nrows, int ncols, const arma::vec& extent, int min_overlap);
RcppExport SEXP _thermal_assess_registration_cpp(SEXP paramsSEXP, SEXP vcoordsSEXP, SEXP r2SEXP, SEXP distortion_centerSEXP, SEXP vvaluesSEXP, SEXP tvaluesSEXP, SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP extentSEXP, SEXP min_overlapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type vcoords(vcoordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type distortion_center(distortion_centerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vvalues(vvaluesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tvalues(tvaluesSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< int >::type min_overlap(min_overlapSEXP);
    rcpp_result_gen = Rcpp::wrap(assess_registration_cpp(params, vcoords, r2, distortion_center, vvalues, tvalues, nrows, ncols, extent, min_overlap));
    return rcpp_result_gen;
END_RCPP
}
// convert_coords_optim_cpp
arma::mat convert_coords_optim_cpp(arma::mat& coords, const arma::vec& optimout, const arma::vec& r2, const arma::vec& distortion_center);
RcppExport SEXP _thermal_convert_coords_optim_cpp(SEXP coordsSEXP, SEXP optimoutSEXP, SEXP r2SEXP, SEXP distortion_centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type optimout(optimoutSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type distortion_center(distortion_centerSEXP);
    rcpp_result_gen = Rcpp::wrap(convert_coords_optim_cpp(coords, optimout, r2, distortion_center));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thermal_assess_transform_cpp", (DL_FUNC) &_thermal_assess_transform_cpp, 10},
    {"_thermal_assess_registration_cpp", (DL_FUNC) &_thermal_assess_registration_cpp, 10},
    {"_thermal_convert_coords_optim_cpp", (DL_FUNC) &_thermal_convert_coords_optim_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_thermal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
