# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assess_transform_cpp <- function(xval, yval, coords, theta, htrans, vtrans, nrows, ncols, extent, min_overlap) {
    .Call(`_thermal_assess_transform_cpp`, xval, yval, coords, theta, htrans, vtrans, nrows, ncols, extent, min_overlap)
}

