# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assess_transform_cpp <- function(xval, yval, coords, theta, htrans, vtrans, nrows, ncols, extent, min_overlap) {
    .Call(`_thermal_assess_transform_cpp`, xval, yval, coords, theta, htrans, vtrans, nrows, ncols, extent, min_overlap)
}

assess_registration_cpp <- function(params, vcoords, r2, distortion_center, vvalues, tvalues, nrows, ncols, extent, min_overlap) {
    .Call(`_thermal_assess_registration_cpp`, params, vcoords, r2, distortion_center, vvalues, tvalues, nrows, ncols, extent, min_overlap)
}

convert_coords_optim_cpp <- function(coords, optimout, r2, distortion_center) {
    .Call(`_thermal_convert_coords_optim_cpp`, coords, optimout, r2, distortion_center)
}

